### ISSUE TITLE
Public key authentication is totally ignored

### ISSUE THREAD

**Issue by Nama** [hatRiot/logalyzer#2]
Failed and successful key authentications aren't parsed.

Add this in ParseUsr():

```
elif "Accepted publickey" in line:
        usr = re.search(r'(\bfor\s)(\w+)', line)
```

And change the first if in the for loop in ParseLogs() to:
`if "Accepted password for" in line or "Accepted publickey for" in line:`

This way, key logins are shown, too. Since I generally disable password-authentication, it doesn't work for me.
Still failed logins aren't shown. You need to look for "Authentication refused", "Invalid user" and "error: Received disconnect". Since only "Invalid user" shows the username, this breaks the whole system of this script.

**Comment by yoiang** [comment]
@Nama the fork I've created parses publickey access: [here](https://github.com/adorkable-forkable/logalyzer)

**Comment by Nama** [comment]
thx @yoiang

**Comment by GoMapur** [comment]
Thx @yoiang
